////////////////////////////////////////////////////////////////////////////////
//
//  YOUR QUILL
//
////////////////////////////////////////////////////////////////////////////////

//#include "Encode64.ipp"
#include "IgCase.ipp"
#include "IterUtf8.ipp"
#include "MaybeCase.ipp"
#include "RevIgCase.ipp"
#include "XCase.ipp"
#include "basic.ipp"
#include "basic32.ipp"
#include "chars.ipp"
#include "chars32.ipp"
#include "copy.ipp"
#include "copy32.ipp"
#include "count.ipp"
#include "count32.ipp"
#include "format.ipp"
#include "format32.ipp"
#include "ios.ipp"
#include "ios32.ipp"
#include "join.ipp"
#include "join32.ipp"
#include "match.ipp"
#include "match32.ipp"
//#include "misc.ipp"
//#include "misc32.ipp"
//#include "parse.ipp"
//#include "parse32.ipp"
#include "split.ipp"
#include "split32.ipp"
#include "testing.ipp"
#include "transform.ipp"
#include "transform32.ipp"
