////////////////////////////////////////////////////////////////////////////////
//
//  YOUR QUILL
//
////////////////////////////////////////////////////////////////////////////////

#include "colors.hpp"
#include "database.hpp"
#include <yq/errors.hpp>

namespace yq::color {
    static struct entry_t {
        std::string_view    name;
        RGB3U8              rgb;
    }  kColors[] = {
        { "Air Force Blue", AirForceBlue },
        { "Alice Blue", AliceBlue },
        { "Alizarin Crimson", AlizarinCrimson },
        { "Almond", Almond },
        { "Amaranth", Amaranth },
        { "Amber", Amber },
        { "American Rose", AmericanRose },
        { "Amethyst", Amethyst },
        { "Android Green", AndroidGreen },
        { "Anti Flash White", AntiFlashWhite },
        { "Antique Brass", AntiqueBrass },
        { "Antique Fuchsia", AntiqueFuchsia },
        { "Antique White", AntiqueWhite },
        { "Ao", Ao },
        { "Apple Green", AppleGreen },
        { "Apricot", Apricot },
        { "Aqua", Aqua },
        { "Aquamarine", Aquamarine },
        { "Army Green", ArmyGreen },
        { "Arylide Yellow", ArylideYellow },
        { "Ash Grey", AshGrey },
        { "Asparagus", Asparagus },
        { "Atomic Tangerine", AtomicTangerine },
        { "Auburn", Auburn },
        { "Aureolin", Aureolin },
        { "Auro Metal Saurus", AuroMetalSaurus },
        { "Awesome", Awesome },
        { "Azure", Azure },
        { "Azure Mist", AzureMist },
        { "Baby Blue", BabyBlue },
        { "Baby Blue Eyes", BabyBlueEyes },
        { "Baby Pink", BabyPink },
        { "Ball Blue", BallBlue },
        { "Banana Mania", BananaMania },
        { "Banana Yellow", BananaYellow },
        { "Battleship Grey", BattleshipGrey },
        { "Bazaar", Bazaar },
        { "Beau Blue", BeauBlue },
        { "Beaver", Beaver },
        { "Beige", Beige },
        { "Bisque", Bisque },
        { "Bistre", Bistre },
        { "Bittersweet", Bittersweet },
        { "Black", Black },
        { "Blanched Almond", BlanchedAlmond },
        { "Bleu De France", BleuDeFrance },
        { "Blizzard Blue", BlizzardBlue },
        { "Blond", Blond },
        { "Blue", Blue },
        { "Blue Bell", BlueBell },
        { "Blue Gray", BlueGray },
        { "Blue Green", BlueGreen },
        { "Blue Purple", BluePurple },
        { "Blue Violet", BlueViolet },
        { "Blush", Blush },
        { "Bole", Bole },
        { "Bondi Blue", BondiBlue },
        { "Bone", Bone },
        { "Boston University Red", BostonUniversityRed },
        { "Bottle Green", BottleGreen },
        { "Boysenberry", Boysenberry },
        { "Brandeis Blue", BrandeisBlue },
        { "Brass", Brass },
        { "Brick Red", BrickRed },
        { "Bright Cerulean", BrightCerulean },
        { "Bright Green", BrightGreen },
        { "Bright Lavender", BrightLavender },
        { "Bright Maroon", BrightMaroon },
        { "Bright Pink", BrightPink },
        { "Bright Turquoise", BrightTurquoise },
        { "Bright Ube", BrightUbe },
        { "Brilliant Lavender", BrilliantLavender },
        { "Brilliant Rose", BrilliantRose },
        { "Brink Pink", BrinkPink },
        { "British Racing Green", BritishRacingGreen },
        { "Bronze", Bronze },
        { "Brown", Brown },
        { "Bubble Gum", BubbleGum },
        { "Bubbles", Bubbles },
        { "Buff", Buff },
        { "Bulgarian Rose", BulgarianRose },
        { "Burgundy", Burgundy },
        { "Burlywood", Burlywood },
        { "Burnt Orange", BurntOrange },
        { "Burnt Sienna", BurntSienna },
        { "Burnt Umber", BurntUmber },
        { "Byzantine", Byzantine },
        { "Byzantium", Byzantium },
        { "CG Blue", CGBlue },
        { "CG Red", CGRed },
        { "Cadet", Cadet },
        { "Cadet Blue", CadetBlue },
        { "Cadet Grey", CadetGrey },
        { "Cadmium Green", CadmiumGreen },
        { "Cadmium Orange", CadmiumOrange },
        { "Cadmium Red", CadmiumRed },
        { "Cadmium Yellow", CadmiumYellow },
        { "Cafe Au Lait", CafeAuLait },
        { "Cafe Noir", CafeNoir },
        { "Cal Poly Pomona Green", CalPolyPomonaGreen },
        { "Cambridge Blue", CambridgeBlue },
        { "Camel", Camel },
        { "Camouflage Green", CamouflageGreen },
        { "Canary", Canary },
        { "Canary Yellow", CanaryYellow },
        { "Candy Apple Red", CandyAppleRed },
        { "Candy Pink", CandyPink },
        { "Capri", Capri },
        { "Caput Mortuum", CaputMortuum },
        { "Cardinal", Cardinal },
        { "Caribbean Green", CaribbeanGreen },
        { "Carmine", Carmine },
        { "Carmine Pink", CarminePink },
        { "Carmine Red", CarmineRed },
        { "Carnation Pink", CarnationPink },
        { "Carnelian", Carnelian },
        { "Carolina Blue", CarolinaBlue },
        { "Carrot Orange", CarrotOrange },
        { "Celadon", Celadon },
        { "Celeste", Celeste },
        { "Celestial Blue", CelestialBlue },
        { "Cerise", Cerise },
        { "Cerise Pink", CerisePink },
        { "Cerulean", Cerulean },
        { "Cerulean Blue", CeruleanBlue },
        { "Chamoisee", Chamoisee },
        { "Champagne", Champagne },
        { "Charcoal", Charcoal },
        { "Chartreuse", Chartreuse },
        { "Cherry", Cherry },
        { "Cherry Blossom Pink", CherryBlossomPink },
        { "Chestnut", Chestnut },
        { "Chocolate", Chocolate },
        { "Chrome Yellow", ChromeYellow },
        { "Cinereous", Cinereous },
        { "Cinnabar", Cinnabar },
        { "Cinnamon", Cinnamon },
        { "Citrine", Citrine },
        { "Classic Rose", ClassicRose },
        { "Cobalt", Cobalt },
        { "Cocoa Brown", CocoaBrown },
        { "Coffee", Coffee },
        { "Columbia Blue", ColumbiaBlue },
        { "Cool Black", CoolBlack },
        { "Cool Grey", CoolGrey },
        { "Copper", Copper },
        { "Copper Rose", CopperRose },
        { "Coquelicot", Coquelicot },
        { "Coral", Coral },
        { "Coral Pink", CoralPink },
        { "Coral Red", CoralRed },
        { "Cordovan", Cordovan },
        { "Corn", Corn },
        { "Cornell Red", CornellRed },
        { "Cornflower", Cornflower },
        { "Cornflower Blue", CornflowerBlue },
        { "Cornsilk", Cornsilk },
        { "Cosmic Latte", CosmicLatte },
        { "Cotton Candy", CottonCandy },
        { "Cream", Cream },
        { "Crimson", Crimson },
        { "Crimson Red", CrimsonRed },
        { "Crimson Glory", CrimsonGlory },
        { "Cyan", Cyan },
        { "Daffodil", Daffodil },
        { "Dandelion", Dandelion },
        { "Dark Blue", DarkBlue },
        { "Dark Brown", DarkBrown },
        { "Dark Byzantium", DarkByzantium },
        { "Dark Candy Apple Red", DarkCandyAppleRed },
        { "Dark Cerulean", DarkCerulean },
        { "Dark Chestnut", DarkChestnut },
        { "Dark Coral", DarkCoral },
        { "Dark Cyan", DarkCyan },
        { "Dark Electric Blue", DarkElectricBlue },
        { "Dark Goldenrod", DarkGoldenrod },
        { "Dark Gray", DarkGray },
        { "Dark Green", DarkGreen },
        { "Dark Jungle Green", DarkJungleGreen },
        { "Dark Khaki", DarkKhaki },
        { "Dark Lava", DarkLava },
        { "Dark Lavender", DarkLavender },
        { "Dark Magenta", DarkMagenta },
        { "Dark Midnight Blue", DarkMidnightBlue },
        { "Dark Olive Green", DarkOliveGreen },
        { "Dark Orange", DarkOrange },
        { "Dark Orchid", DarkOrchid },
        { "Dark Pastel Blue", DarkPastelBlue },
        { "Dark Pastel Green", DarkPastelGreen },
        { "Dark Pastel Purple", DarkPastelPurple },
        { "Dark Pastel Red", DarkPastelRed },
        { "Dark Pink", DarkPink },
        { "Dark Powder Blue", DarkPowderBlue },
        { "Dark Raspberry", DarkRaspberry },
        { "Dark Red", DarkRed },
        { "Dark Salmon", DarkSalmon },
        { "Dark Scarlet", DarkScarlet },
        { "Dark SeaGreen", DarkSeaGreen },
        { "Dark Sienna", DarkSienna },
        { "Dark SlateBlue", DarkSlateBlue },
        { "Dark SlateGray", DarkSlateGray },
        { "Dark SpringGreen", DarkSpringGreen },
        { "Dark Tan", DarkTan },
        { "Dark Tangerine", DarkTangerine },
        { "Dark Taupe", DarkTaupe },
        { "Dark TerraCotta", DarkTerraCotta },
        { "Dark Turquoise", DarkTurquoise },
        { "Dark Violet", DarkViolet },
        { "Dartmouth Green", DartmouthGreen },
        { "Davy Grey", DavyGrey },
        { "Debian Red", DebianRed },
        { "Deep Carmine", DeepCarmine },
        { "Deep Carmine Pink", DeepCarminePink },
        { "Deep Carrot Orange", DeepCarrotOrange },
        { "Deep Cerise", DeepCerise },
        { "Deep Champagne", DeepChampagne },
        { "Deep Chestnut", DeepChestnut },
        { "Deep Coffee", DeepCoffee },
        { "Deep Dark Gray", DeepDarkGray },
        { "Deep Fuchsia", DeepFuchsia },
        { "Deep Jungle Green", DeepJungleGreen },
        { "Deep Lilac", DeepLilac },
        { "Deep Magenta", DeepMagenta },
        { "Deep Peach", DeepPeach },
        { "Deep Pink", DeepPink },
        { "Deep Saffron", DeepSaffron },
        { "Deep Sky Blue", DeepSkyBlue },
        { "Denim", Denim },
        { "Desert", Desert },
        { "Desert Sand", DesertSand },
        { "Dim Gray", DimGray },
        { "Dodger Blue", DodgerBlue },
        { "Dogwood Rose", DogwoodRose },
        { "Dollar Bill", DollarBill },
        { "Drab", Drab },
        { "Duke Blue", DukeBlue },
        { "Earth Yellow", EarthYellow },
        { "Ecru", Ecru },
        { "Eggplant", Eggplant },
        { "Eggshell", Eggshell },
        { "Egyptian Blue", EgyptianBlue },
        { "Electric Blue", ElectricBlue },
        { "Electric Crimson", ElectricCrimson },
        { "Electric Cyan", ElectricCyan },
        { "Electric Green", ElectricGreen },
        { "Electric Indigo", ElectricIndigo },
        { "Electric Lavender", ElectricLavender },
        { "Electric Lime", ElectricLime },
        { "Electric Purple", ElectricPurple },
        { "Electric Ultramarine", ElectricUltramarine },
        { "Electric Violet", ElectricViolet },
        { "Electric Yellow", ElectricYellow },
        { "Emerald", Emerald },
        { "Eton Blue", EtonBlue },
        { "Fallow", Fallow },
        { "Falu Red", FaluRed },
        { "Famous", Famous },
        { "Fandango", Fandango },
        { "Fashion Fuchsia", FashionFuchsia },
        { "Fawn", Fawn },
        { "Feldgrau", Feldgrau },
        { "Fern", Fern },
        { "Fern Green", FernGreen },
        { "Ferrari Red", FerrariRed },
        { "Field Drab", FieldDrab },
        { "Fire Engine Red", FireEngineRed },
        { "Firebrick", Firebrick },
        { "Flame", Flame },
        { "Flamingo Pink", FlamingoPink },
        { "Flavescent", Flavescent },
        { "Flax", Flax },
        { "Floral White", FloralWhite },
        { "Fluorescent Orange", FluorescentOrange },
        { "Fluorescent Pink", FluorescentPink },
        { "Fluorescent Yellow", FluorescentYellow },
        { "Folly", Folly },
        { "Forest Green", ForestGreen },
        { "French Beige", FrenchBeige },
        { "French Blue", FrenchBlue },
        { "French Lilac", FrenchLilac },
        { "French Rose", FrenchRose },
        { "Fuchsia", Fuchsia },
        { "Fuchsia Pink", FuchsiaPink },
        { "Fulvous", Fulvous },
        { "Fuzzy Wuzzy", FuzzyWuzzy },
        { "Gainsboro", Gainsboro },
        { "Gamboge", Gamboge },
        { "GhostWhite", GhostWhite },
        { "Ginger", Ginger },
        { "Glaucous", Glaucous },
        { "Glitter", Glitter },
        { "Gold", Gold },
        { "Golden Brown", GoldenBrown },
        { "Golden Poppy", GoldenPoppy },
        { "Golden Yellow", GoldenYellow },
        { "Goldenrod", Goldenrod },
        { "Granny Smith Apple", GrannySmithApple },
        { "Gray", Gray },
        { "Gray Asparagus", GrayAsparagus },
        { "Green", Green },
        { "Green Blue", GreenBlue },
        { "Green Yellow", GreenYellow },
        { "Grullo", Grullo },
        { "Guppie Green", GuppieGreen },
        { "Halaya Ube", HalayaUbe },
        { "Han Blue", HanBlue },
        { "Han Purple", HanPurple },
        { "Hansa Yellow", HansaYellow },
        { "Harlequin", Harlequin },
        { "Harvard Crimson", HarvardCrimson },
        { "Harvest Gold", HarvestGold },
        { "Heart Gold", HeartGold },
        { "Heliotrope", Heliotrope },
        { "Hollywood Cerise", HollywoodCerise },
        { "Honeydew", Honeydew },
        { "Hooker Green", HookerGreen },
        { "Hot Magenta", HotMagenta },
        { "Hot Pink", HotPink },
        { "Hunter Green", HunterGreen },
        { "Icterine", Icterine },
        { "Inchworm", Inchworm },
        { "India Green", IndiaGreen },
        { "Indian Red", IndianRed },
        { "Indian Yellow", IndianYellow },
        { "Indigo", Indigo },
        { "International Klein Blue", InternationalKleinBlue },
        { "International Orange", InternationalOrange },
        { "Iris", Iris },
        { "Isabelline", Isabelline },
        { "Islamic Green", IslamicGreen },
        { "Ivory", Ivory },
        { "Jade", Jade },
        { "Jasmine", Jasmine },
        { "Jasper", Jasper },
        { "Jazzberry Jam", JazzberryJam },
        { "Jonquil", Jonquil },
        { "JuneBud", JuneBud },
        { "Jungle Green", JungleGreen },
        { "KU Crimson", KUCrimson },
        { "Kelly Green", KellyGreen },
        { "Khaki", Khaki },
        { "La Salle Green", LaSalleGreen },
        { "Languid Lavender", LanguidLavender },
        { "Lapis Lazuli", LapisLazuli },
        { "Laser Lemon", LaserLemon },
        { "Laurel Green", LaurelGreen },
        { "Lava", Lava },
        { "Lavender", Lavender },
        { "Lavender Blue", LavenderBlue },
        { "Lavender Blush", LavenderBlush },
        { "Lavender Gray", LavenderGray },
        { "Lavender Indigo", LavenderIndigo },
        { "Lavender Magenta", LavenderMagenta },
        { "Lavender Mist", LavenderMist },
        { "Lavender Pink", LavenderPink },
        { "Lavender Purple", LavenderPurple },
        { "Lavender Rose", LavenderRose },
        { "Lawn Green", LawnGreen },
        { "Lemon", Lemon },
        { "Lemon Yellow", LemonYellow },
        { "Lemon Chiffon", LemonChiffon },
        { "Lemon Lime", LemonLime },
        { "Light Crimson", LightCrimson },
        { "Light Thulian Pink", LightThulianPink },
        { "Light Apricot", LightApricot },
        { "Light Blue", LightBlue },
        { "Light Brown", LightBrown },
        { "Light Carmine Pink", LightCarminePink },
        { "Light Coral", LightCoral },
        { "Light Cornflower Blue", LightCornflowerBlue },
        { "Light Cyan", LightCyan },
        { "Light Fuchsia Pink", LightFuchsiaPink },
        { "Light Goldenrod Yellow", LightGoldenrodYellow },
        { "Light Gray", LightGray },
        { "Light Green", LightGreen },
        { "Light Khaki", LightKhaki },
        { "Light Pastel Purple", LightPastelPurple },
        { "Light Pink", LightPink },
        { "Light Salmon", LightSalmon },
        { "Light Salmon Pink", LightSalmonPink },
        { "Light Sea Green", LightSeaGreen },
        { "Light Sky Blue", LightSkyBlue },
        { "Light Slate Gray", LightSlateGray },
        { "Light Taupe", LightTaupe },
        { "Light Yellow", LightYellow },
        { "Lilac", Lilac },
        { "Lime", Lime },
        { "Lime Green", LimeGreen },
        { "Lincoln Green", LincolnGreen },
        { "Linen", Linen },
        { "Lion", Lion },
        { "Liver", Liver },
        { "Lust", Lust },
        { "MSU Green", MSUGreen },
        { "Macaroni And Cheese", MacaroniAndCheese },
        { "Magenta", Magenta },
        { "Magic Mint", MagicMint },
        { "Magnolia", Magnolia },
        { "Mahogany", Mahogany },
        { "Maize", Maize },
        { "Majorelle Blue", MajorelleBlue },
        { "Malachite", Malachite },
        { "Manatee", Manatee },
        { "Mango Tango", MangoTango },
        { "Mantis", Mantis },
        { "Maroon", Maroon },
        { "Mauve", Mauve },
        { "Mauve Taupe", MauveTaupe },
        { "Mauvelous", Mauvelous },
        { "Maya Blue", MayaBlue },
        { "Meat Brown", MeatBrown },
        { "Medium Aquamarine", MediumAquamarine },
        { "Medium Blue", MediumBlue },
        { "Medium Candy Apple Red", MediumCandyAppleRed },
        { "Medium Carmine", MediumCarmine },
        { "Medium Champagne", MediumChampagne },
        { "Medium Electric Blue", MediumElectricBlue },
        { "Medium Jungle Green", MediumJungleGreen },
        { "Medium Lavender Magenta", MediumLavenderMagenta },
        { "Medium Orchid", MediumOrchid },
        { "Medium Persian Blue", MediumPersianBlue },
        { "Medium Purple", MediumPurple },
        { "Medium Red Violet", MediumRedViolet },
        { "Medium Sea Green", MediumSeaGreen },
        { "Medium Slate Blue", MediumSlateBlue },
        { "Medium Spring Bud", MediumSpringBud },
        { "Medium Spring Green", MediumSpringGreen },
        { "Medium Taupe", MediumTaupe },
        { "Medium Teal Blue", MediumTealBlue },
        { "Medium Turquoise", MediumTurquoise },
        { "Medium Violet Red", MediumVioletRed },
        { "Melon", Melon },
        { "Midnight Blue", MidnightBlue },
        { "Midnight Green", MidnightGreen },
        { "Mikado Yellow", MikadoYellow },
        { "Mint", Mint },
        { "Mint Cream", MintCream },
        { "Mint Green", MintGreen },
        { "Misty Rose", MistyRose },
        { "Moccasin", Moccasin },
        { "Mode Beige", ModeBeige },
        { "Moonstone Blue", MoonstoneBlue },
        { "Mordant Red 19", MordantRed19 },
        { "Moss Green", MossGreen },
        { "Mountain Meadow", MountainMeadow },
        { "Mountbatten Pink", MountbattenPink },
        { "Mulberry", Mulberry },
        { "Munsell", Munsell },
        { "Mustard", Mustard },
        { "Myrtle", Myrtle },
        { "Nadeshiko Pink", NadeshikoPink },
        { "Napier Green", NapierGreen },
        { "Naples Yellow", NaplesYellow },
        { "Navajo White", NavajoWhite },
        { "Navy Blue", NavyBlue },
        { "Neon Carrot", NeonCarrot },
        { "Neon Fuchsia", NeonFuchsia },
        { "Neon Green", NeonGreen },
        { "Non Photo Blue", NonPhotoBlue },
        { "North Texas Green", NorthTexasGreen },
        { "Ocean Boat Blue", OceanBoatBlue },
        { "Ochre", Ochre },
        { "Offic eGreen", OfficeGreen },
        { "Old Gold", OldGold },
        { "Old Lace", OldLace },
        { "Old Lavender", OldLavender },
        { "Old Mauve", OldMauve },
        { "Old Rose", OldRose },
        { "Olive", Olive },
        { "Olive Drab", OliveDrab },
        { "Olive Green", OliveGreen },
        { "Olivine", Olivine },
        { "Onyx", Onyx },
        { "OperaMauve", OperaMauve },
        { "Orange", Orange },
        { "Orange Yellow", OrangeYellow },
        { "Orange Peel", OrangePeel },
        { "Orange Red", OrangeRed },
        { "Orchid", Orchid },
        { "Otter Brown", OtterBrown },
        { "Outer Space", OuterSpace },
        { "Outrageous Orange", OutrageousOrange },
        { "Oxford Blue", OxfordBlue },
        { "Pacific Blue", PacificBlue },
        { "Pakistan Green", PakistanGreen },
        { "Palatinate Blue", PalatinateBlue },
        { "Palatinate Purple", PalatinatePurple },
        { "Pale Aqua", PaleAqua },
        { "Pale Blue", PaleBlue },
        { "Pale Brown", PaleBrown },
        { "Pale Carmine", PaleCarmine },
        { "Pale Cerulean", PaleCerulean },
        { "Pale Chestnut", PaleChestnut },
        { "Pale Copper", PaleCopper },
        { "Pale Cornflower Blue", PaleCornflowerBlue },
        { "Pale Gold", PaleGold },
        { "Pale Goldenrod", PaleGoldenrod },
        { "Pale Green", PaleGreen },
        { "Pale Lavender", PaleLavender },
        { "Pale Magenta", PaleMagenta },
        { "Pale Pink", PalePink },
        { "Pale Plum", PalePlum },
        { "Pale RedViolet", PaleRedViolet },
        { "Pale Robin Egg Blue", PaleRobinEggBlue },
        { "Pale Silver", PaleSilver },
        { "Pale Spring Bud", PaleSpringBud },
        { "Pale Taupe", PaleTaupe },
        { "Pale Violet Red", PaleVioletRed },
        { "Pansy Purple", PansyPurple },
        { "Papaya Whip", PapayaWhip },
        { "Paris Green", ParisGreen },
        { "Pastel Blue", PastelBlue },
        { "Pastel Brown", PastelBrown },
        { "Pastel Gray", PastelGray },
        { "Pastel Green", PastelGreen },
        { "Pastel Magenta", PastelMagenta },
        { "Pastel Orange", PastelOrange },
        { "Pastel Pink", PastelPink },
        { "Pastel Purple", PastelPurple },
        { "Pastel Red", PastelRed },
        { "Pastel Violet", PastelViolet },
        { "Pastel Yellow", PastelYellow },
        { "Patriarch", Patriarch },
        { "Payne Grey", PayneGrey },
        { "Peach", Peach },
        { "Peach Puff", PeachPuff },
        { "Peach Yellow", PeachYellow },
        { "Pear", Pear },
        { "Pearl", Pearl },
        { "Pearl Aqua", PearlAqua },
        { "Peridot", Peridot },
        { "Periwinkle", Periwinkle },
        { "Persian Blue", PersianBlue },
        { "Persian Indigo", PersianIndigo },
        { "Persian Orange", PersianOrange },
        { "Persian Pink", PersianPink },
        { "Persian Plum", PersianPlum },
        { "Persian Red", PersianRed },
        { "Persian Rose", PersianRose },
        { "Phlox", Phlox },
        { "Phthalo Blue", PhthaloBlue },
        { "Phthalo Green", PhthaloGreen },
        { "Piggy Pink", PiggyPink },
        { "Pine Green", PineGreen },
        { "Pink", Pink },
        { "Pink Flamingo", PinkFlamingo },
        { "Pink Sherbet", PinkSherbet },
        { "Pink Pearl", PinkPearl },
        { "Pistachio", Pistachio },
        { "Platinum", Platinum },
        { "Plum", Plum },
        { "Portland Orange", PortlandOrange },
        { "Powder Blue", PowderBlue },
        { "Princeton Orange", PrincetonOrange },
        { "Prussian Blue", PrussianBlue },
        { "Psychedelic Purple", PsychedelicPurple },
        { "Puce", Puce },
        { "Pumpkin", Pumpkin },
        { "Purple", Purple },
        { "Purple Heart", PurpleHeart },
        { "Purple Mountains Majesty", PurpleMountainsMajesty },
        { "Purple Mountain Majesty", PurpleMountainMajesty },
        { "Purple Pizzazz", PurplePizzazz },
        { "Purple Taupe", PurpleTaupe },
        { "Rackley", Rackley },
        { "RadicalRed", RadicalRed },
        { "Raspberry", Raspberry },
        { "Raspberry Glace", RaspberryGlace },
        { "Raspberry Pink", RaspberryPink },
        { "Raspberry Rose", RaspberryRose },
        { "RawSienna", RawSienna },
        { "Razzle Dazzle Rose", RazzleDazzleRose },
        { "Razzmatazz", Razzmatazz },
        { "Red", Red },
        { "Red Orange", RedOrange },
        { "Red Brown", RedBrown },
        { "Red Violet", RedViolet },
        { "Rich Black", RichBlack },
        { "Rich Carmine", RichCarmine },
        { "Rich Electric Blue", RichElectricBlue },
        { "Rich Lilac", RichLilac },
        { "Rich Maroon", RichMaroon },
        { "Rifle Green", RifleGreen },
        { "Robin Egg Blue", RobinEggBlue },
        { "Rose", Rose },
        { "Rose Bonbon", RoseBonbon },
        { "Rose Ebony", RoseEbony },
        { "Rose Gold", RoseGold },
        { "Rose Madder", RoseMadder },
        { "Rose Pink", RosePink },
        { "Rose Quartz", RoseQuartz },
        { "Rose Taupe", RoseTaupe },
        { "Rose Vale", RoseVale },
        { "Rosewood", Rosewood },
        { "Rosso Corsa", RossoCorsa },
        { "Rosy Brown", RosyBrown },
        { "Royal Azure", RoyalAzure },
        { "Royal Blue", RoyalBlue },
        { "Royal Fuchsia", RoyalFuchsia },
        { "Royal Purple", RoyalPurple },
        { "Ruby", Ruby },
        { "Ruddy", Ruddy },
        { "Ruddy Brown", RuddyBrown },
        { "Ruddy Pink", RuddyPink },
        { "Rufous", Rufous },
        { "Russet", Russet },
        { "Rust", Rust },
        { "Sacramento State Green", SacramentoStateGreen },
        { "Saddle Brown", SaddleBrown },
        { "Safety Orange", SafetyOrange },
        { "Saffron", Saffron },
        { "Saint Patrick Blue", SaintPatrickBlue },
        { "Salmon", Salmon },
        { "Salmon Pink", SalmonPink },
        { "Sand", Sand },
        { "Sand Dune", SandDune },
        { "Sandstorm", Sandstorm },
        { "Sandy Brown", SandyBrown },
        { "Sandy Taupe", SandyTaupe },
        { "Sap Green", SapGreen },
        { "Sapphire", Sapphire },
        { "Satin Sheen Gold", SatinSheenGold },
        { "Scarlet", Scarlet },
        { "School Bus Yellow", SchoolBusYellow },
        { "Screamin Green", ScreaminGreen },
        { "Sea Blue", SeaBlue },
        { "Sea Green", SeaGreen },
        { "Seal Brown", SealBrown },
        { "Seashell", Seashell },
        { "Selective Yellow", SelectiveYellow },
        { "Sepia", Sepia },
        { "Shadow", Shadow },
        { "Shamrock", Shamrock },
        { "Shamrock Green", ShamrockGreen },
        { "Shocking Pink", ShockingPink },
        { "Sienna", Sienna },
        { "Silver", Silver },
        { "Sinopia", Sinopia },
        { "Skobeloff", Skobeloff },
        { "Sky Blue", SkyBlue },
        { "Sky Magenta", SkyMagenta },
        { "Slate Blue", SlateBlue },
        { "Slate Gray", SlateGray },
        { "Smalt", Smalt },
        { "Smokey Topaz", SmokeyTopaz },
        { "Smoky Black", SmokyBlack },
        { "Snow", Snow },
        { "Spiro Disco Ball", SpiroDiscoBall },
        { "Spring Bud", SpringBud },
        { "Spring Green", SpringGreen },
        { "Steel Blue", SteelBlue },
        { "Stil De Grain Yellow", StilDeGrainYellow },
        { "Stizza", Stizza },
        { "Stormcloud", Stormcloud },
        { "Straw", Straw },
        { "Sunglow", Sunglow },
        { "Sunset", Sunset },
        { "Sunset Orange", SunsetOrange },
        { "Tan", Tan },
        { "Tangelo", Tangelo },
        { "Tangerine", Tangerine },
        { "Tangerine Yellow", TangerineYellow },
        { "Taupe", Taupe },
        { "Taupe Gray", TaupeGray },
        { "Tawny", Tawny },
        { "Tea Green", TeaGreen },
        { "Tea Rose", TeaRose },
        { "Teal", Teal },
        { "Teal Blue", TealBlue },
        { "Teal Green", TealGreen },
        { "Terra Cotta", TerraCotta },
        { "Thistle", Thistle },
        { "Thulian Pink", ThulianPink },
        { "Tickle Me Pink", TickleMePink },
        { "Tiffany Blue", TiffanyBlue },
        { "Tiger Eye", TigerEye },
        { "Timberwolf", Timberwolf },
        { "Titanium Yellow", TitaniumYellow },
        { "Tomato", Tomato },
        { "Toolbox", Toolbox },
        { "Topaz", Topaz },
        { "Tractor Red", TractorRed },
        { "Trolley Grey", TrolleyGrey },
        { "Tropical Rain Forest", TropicalRainForest },
        { "True Blue", TrueBlue },
        { "Tufts Blue", TuftsBlue },
        { "Tumbleweed", Tumbleweed },
        { "Turkish Rose", TurkishRose },
        { "Turquoise", Turquoise },
        { "Turquoise Blue", TurquoiseBlue },
        { "Turquoise Green", TurquoiseGreen },
        { "Tuscan Red", TuscanRed },
        { "Twilight Lavender", TwilightLavender },
        { "Tyrian Purple", TyrianPurple },
        { "UA Blue", UABlue },
        { "UA Red", UARed },
        { "UC Gold", UniversityOfCaliforniaGold },
        { "UCLA Blue", UCLABlue },
        { "UCLA Gold", UCLAGold },
        { "UFO Green", UFOGreen },
        { "UP Forest Green", UPForestGreen },
        { "UP Maroon", UPMaroon },
        { "USC Cardinal", USCCardinal },
        { "USC Gold", USCGold },
        { "Ube", Ube },
        { "Ultra Pink", UltraPink },
        { "Ultramarine", Ultramarine },
        { "Ultramarine Blue", UltramarineBlue },
        { "Umber", Umber },
        { "United Nations Blue", UnitedNationsBlue },
        { "University Of California Gold", UniversityOfCaliforniaGold },
        { "Unmellow Yellow", UnmellowYellow },
        { "Upsdell Red", UpsdellRed },
        { "Urobilin", Urobilin },
        { "Utah Crimson", UtahCrimson },
        { "Vanilla", Vanilla },
        { "Vegas Gold", VegasGold },
        { "Venetian Red", VenetianRed },
        { "Verdigris", Verdigris },
        { "Vermilion", Vermilion },
        { "Veronica", Veronica },
        { "Violet", Violet },
        { "Violet Blue", VioletBlue },
        { "Violet Red", VioletRed },
        { "Viridian", Viridian },
        { "Vivid Auburn", VividAuburn },
        { "Vivid Burgundy", VividBurgundy },
        { "Vivid Cerise", VividCerise },
        { "Vivid Tangerine", VividTangerine },
        { "Vivid Violet", VividViolet },
        { "Warm Black", WarmBlack },
        { "Wate rspout", Waterspout },
        { "Wenge", Wenge },
        { "Wheat", Wheat },
        { "White", White },
        { "White Smoke", WhiteSmoke },
        { "Wild Strawberry", WildStrawberry },
        { "Wild Watermelon", WildWatermelon },
        { "Wild BlueYonder", WildBlueYonder },
        { "Wine", Wine },
        { "Wisteria", Wisteria },
        { "Xanadu", Xanadu },
        { "Yale Blue", YaleBlue },
        { "Yellow", Yellow },
        { "Yellow Orange", YellowOrange },
        { "Yellow Green", YellowGreen },
        { "Zaffre", Zaffre },
        { "Zinnwaldite Brown", ZinnwalditeBrown },
    };
    
    static color_map_t create_database()
    {
        color_map_t ret;
        for(auto& x : kColors)
            ret[x.name] = x.rgb;
        return ret;
    }

    const color_map_t&  database()
    {
        static color_map_t  s_db    = create_database();
        return s_db;
    }
    
    rgb3u8_x            lookup(std::string_view k)
    {
        static const color_map_t&  db  = database();
        auto i = db.find(k);
        if(i != db.end())
            return i->second;
        return errors::key_not_found();
    }
    
}
